### ISSUE TITLE
Error creating Redis instance due to api-version

### ISSUE THREAD

**Issue by Rosenberg96** [crossplane/provider-azure#204]
### What happened?

When trying to provision a Redis instance on Azure the process fails. The following is the full output 
```
observe failed: cannot get Redis instance from Azure API:
        redis.Client#Get: Failure responding to request: StatusCode=400 --
        Original Error: autorest/azure: Service returned an error. Status=400
        Code="InvalidApiVersionParameter" Message="The api-version '2018-03-01'
        is invalid. The supported versions are
        '2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```
### How can we reproduce it?

The following Redis definitions was used:

```
apiVersion: cache.azure.crossplane.io/v1beta1
kind: Redis
metadata:
  name: redis
  namespace: development
spec:
  forProvider:
    location: West Europe
    sku:
      capacity: 1
      family: C
      name: Basic
  providerConfigRef:
    name: provider-azure
  providerRef:
    name: provider-azure
  writeConnectionSecretToRef:
    name: redis-secret
    namespace: development
```

### What environment did it happen in?
Crossplane version: 0.14-alpha

I believe the following lines defines the api-version, which should now be updated: https://github.com/crossplane/provider-azure/blob/master/pkg/clients/redis/redis.go#L22

**Comment by negz** [comment]
Thanks for catching this @Rosenberg96! I suppose Azure must have dropped support for the API version we were using. 🤔 It definitely worked last time I tried it (which was a while ago at this point). I'll take a look at updating this.

**Comment by negz** [comment]
Interestingly I'm able to create the following using the master build of provider-azure:

```yaml
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: redis-example
spec:
  location: West US 2
---
apiVersion: cache.azure.crossplane.io/v1beta1
kind: Redis
metadata:
  name: example
  labels:
    example: "true"
spec:
  forProvider:
    resourceGroupNameRef:
      name: redis-example
    location: West US 2
    sku:
      name: Basic
      family: C
      capacity: 0
    enableNonSslPort: true
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-cache
```

I wonder why my example works and yours does not. Perhaps the API version needs to be enabled at the account level, ala GCP APIs? Or perhaps the API works in West US 2 but not West Europe? 🤔
