### ISSUE TITLE
PostgreSQLServer ConnectionSecret is missing the port

### ISSUE THREAD

**Issue by haraldatbmw** [crossplane/provider-azure#224]
### What happened?
When crossplane creates a Azure PostgreSQLServer it creates an additional connection-secret.
The secret contains endpoint, username and passwort but **port** is missing.

### How can we reproduce it?
Create a manifest like this and look inside the secret crossplane-system/crossplane-postgresql-conn.

```
apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: crossplane-postgresql
spec:
  forProvider:
    createMode: Default
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: crossplane-resourcegroup
    location: westeurope
    sslEnforcement: Disabled
    version: "11"
    sku:
      tier: GeneralPurpose
      capacity: 2
      family: Gen5  
    storageProfile:
      backupRetentionDays: 35
      geoRedundantBackup: Disabled
      storageAutogrow: Disabled
      storageMB: 5120
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: crossplane-postgresql-conn
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: 1.0.0
