### ISSUE TITLE
Storage Account resource does not report as Ready

### ISSUE THREAD

**Issue by turkenh** [crossplane/provider-azure#251]
### What happened?

Created a `StorageAccount` expecting it to be ready. I could see the resource as `Succeeded` on the console but managed resource never reports ready.

<img width="1363" alt="Screen Shot 2021-05-28 at 23 03 22" src="https://user-images.githubusercontent.com/9900707/120036502-e9388980-c008-11eb-9823-6aca024993e5.png">

<img width="928" alt="Screen Shot 2021-05-28 at 23 03 36" src="https://user-images.githubusercontent.com/9900707/120036525-f190c480-c008-11eb-9419-cf47280f9d8f.png">
 
### How can we reproduce it?

Create with manifests below:

```
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: hasan-example-rg
spec:
  location: West US 2
  providerConfigRef:
    name: example
---
apiVersion: storage.azure.crossplane.io/v1alpha3
kind: Account
metadata:
  name: hasanexampleacc
  labels:
    example: "true"
spec:
  resourceGroupName: hasan-example-rg
  storageAccountSpec:
    kind: Storage
    location: West US 2
    sku:
      name: Standard_LRS
      tier: Standard
    tags:
      application: crossplane
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: exampleacc
```
### What environment did it happen in?
Crossplane version: 1.2.1
Provider version: v0.17.0-rc.0.4.gdd8d907

[describe-and-logs.txt](https://github.com/crossplane/provider-azure/files/6563118/describe-and-logs.txt)
