### ISSUE TITLE
Infinite update loop when the minimalTlsVersion field value is wrong in PostgreSQLServer 

### ISSUE THREAD

**Issue by G5Olivieri** [crossplane/provider-azure#295]
### What happened?

The first note is that the value of the `minimalTlsVersion` is wrong in the example YAML file. The possible values to these field are TLS1_0, TLS1_1, TLS1_2 and TLSEnforcementDisabled. I think this is influencing the error.

When the `minimalTlsVersion` field is defined with wrong value the Azure API set this field with `TLSEnforcementDisabled` and the IsUpToDate returns always false because the managed resource is different from the provider resource. So the Reconcile falls into update flow and tries to update this field, falling into the infinite loop.

When the `sslEnforcement` field is enabled e `minimalTlsVersion` is not `TLSEnforcementDisabled` value also generates this bug. 

When is in infinite update loop is not possible update managed resource, only to delete.

### Scenario 1

With `sslEnforcement` enabled:

```yaml
apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: example-psql
  labels:
    example: "true"
spec:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: example-rg
    location: West US 2
    minimalTlsVersion: TLS12 # wrong value
    sslEnforcement: Enabled
    version: "9.6"
    sku:
      # Note that Basic servers do not support virtual network rules
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-psql
  providerConfigRef:
    name: example
```

### Scenario 2

With `sslEnforcement` disabled:

```yaml
apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: example-psql
  labels:
    example: "true"
spec:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: example-rg
    location: West US 2
    minimalTlsVersion: TLS1_2 # Any value other than `TLSEnforcementDisabled` 
    sslEnforcement: Disabled
    version: "9.6"
    sku:
      # Note that Basic servers do not support virtual network rules
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-psql
  providerConfigRef:
    name: example
```

### What environment did it happen in?
Crossplane version:
